env:
  global:
    - LOGSTASH_DOCKER_IMAGE="logstash/logstash"
    - LOGSTASH_DOCKER_REGISTRY="docker.elastic.co"
    - LOGSTASH_DOCKER_VERSION="5.4.1"
    - LOGSTASH_DOCKER_ENV="XPACK_MONITORING_ENABLED=false"
    - LOGSTASH_PIPELINE_DIR="docker/logstash/pipeline"
    - LOG_TEST_DIR=""

sudo: required

language: java

services:
  - docker

before_install:
- docker pull ${LOGSTASH_DOCKER_REGISTRY}/${LOGSTASH_DOCKER_IMAGE}:${LOGSTASH_DOCKER_VERSION}
- docker run -d 
  -v ${TRAVIS_BUILD_DIR}/${LOG_PIPELINE_DIR}:/usr/share/logstash/pipeline 
  -e ${LOGSTASH_DOCKER_ENV} 
  ${LOGSTASH_DOCKER_REGISTRY}/${LOGSTASH_DOCKER_IMAGE}:${LOGSTASH_DOCKER_VERSION}
- docker ps
