env:
- LOGSTASH_DOCKER_IMAGE="logstash/logstash"
- LOGSTASH_DOCKER_REGISTRY="docker.elactic.co"
- LOGSTASH_DOCKER_VERSION="5.4.1"

sudo: required

language: java

services:
  - docker

before_install:
- docker pull ${LOGSTASH_DOCKER_REGISTRY}/${LOGSTASH_DOCKER_IMAGE}:${LOGSTASH_DOCKER_VERSION}
